Pizzaria/Models/Customer.cs
namespace Pizzaria.Models
{
    public class Customer
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string UserName { get; set; }

        public string Password { get; set; }
    }
}

Pizzaria/Models/Order.cs
namespace Pizzaria.Models
{
    public class Order
    {
        public const int DoubleCheesePrice = 2;
        public const int BeefPrice = 5;
        public const int TomatoPrice = 1;

        public int Id { get; set; }

        public int CurrentCustomerId { get; set; }

        public int PizzaId { get; set; }

        public bool IsDoubleCheese { get; set; }

        public bool IsTomato { get; set; }

        public bool IsBeef { get; set; }

        public Pizza Pizza { get; set; }

        public float TotalPrice
        {
            get
            {
                if (Pizza is null)
                {
                    return 0;
                }

                float total = Pizza.BasePrice;
                if (IsDoubleCheese)
                {
                    total += DoubleCheesePrice;
                }

                if (IsTomato)
                {
                    total += TomatoPrice;
                }

                if (IsBeef)
                {
                    total += BeefPrice;
                }

                return total;
            }
        }
    }
}

Pizzaria/Models/Pizza.cs
namespace Pizzaria.Models
{
    public class Pizza
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public float BasePrice { get; set; } = 5;
    }
}

Pizzaria/Pages/CreateOrder.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Pizzaria.Models;
using Pizzaria.Repositories;

namespace Pizzaria.Pages
{
    public class CreateOrderModel : PageModelBase
    {
        private readonly IRepository<Pizza> _pizzaRepository;
        private readonly IRepository<Order> _orderRepository;

        public CreateOrderModel(IRepository<Pizza> pizzaRepository, IRepository<Order> orderRepository)
        {
            _pizzaRepository = pizzaRepository;
            _orderRepository = orderRepository;
        }

        [BindProperty]
        public Order CurrentOrder { get; set; }

        [BindProperty]
        public Pizza SelectedPizza { get; set; }

        public IActionResult OnGet(int? pizzaId)
        {
            if (!pizzaId.HasValue)
            {
                return NotFound();
            }

            SelectedPizza = _pizzaRepository.FirstOrDefault(p => p.Id == pizzaId);

            if (SelectedPizza is null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            int? customerId = GetUserId();
            if (_orderRepository.IsEmpty && SelectedPizza is null)
            {
                return Page();
            }

            CurrentOrder.CurrentCustomerId = customerId.Value;
            CurrentOrder.PizzaId = SelectedPizza.Id;

            _orderRepository.AddEntity(CurrentOrder);

            await _orderRepository.SaveChanges();

            return RedirectToPage(PageNames.Index);
        }
    }
}

Pizzaria/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Pizzaria.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pizzaria/Pages/Final.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pizzaria.Models;
using Pizzaria.Repositories;

namespace Pizzaria.Pages
{
    [BindProperties(SupportsGet = true)]
    public class FinalModel : PageModelBase
    {
        private readonly IRepository<Order> _orderRepository;

        public FinalModel(IRepository<Order> orderRepository)
        {
            _orderRepository = orderRepository;
        }

        [BindProperty]
        public List<Order> Orders { get; set; } = new List<Order>();

        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            if (id.HasValue)
            {
                var order = _orderRepository.FirstOrDefault(o => o.Id == id.Value);
                if (order is not null)
                {
                    _orderRepository.RemoveEntity(order);
                    await _orderRepository.SaveChanges();
                }
            }

            return RedirectToPage(PageNames.Final);
        }

        public void OnGet()
        {
            int? customerId = GetUserId();

            if (customerId.HasValue)
            {
                Orders = _orderRepository
                    .Where(o => o.CurrentCustomerId == customerId)
                    .Include(o => o.Pizza)
                    .ToList();
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            int? customerId = GetUserId();

            if (customerId.HasValue)
            {
                _orderRepository.RemoveRange(_orderRepository.Where(o => o.CurrentCustomerId == customerId));
                await _orderRepository.SaveChanges();
            }

            return RedirectToPage(PageNames.ThankYou);
        }
    }
}

Pizzaria/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Pizzaria.Models;
using Pizzaria.Repositories;

namespace Pizzaria.Pages
{
    public class IndexModel : PageModelBase
    {
        public bool HasOrders { get; private set; }

        public List<Pizza> PizzaList = new List<Pizza>();
        private readonly IRepository<Pizza> _pizzaRepository;
        private readonly IRepository<Order> _orderRepository;
        private readonly IRepository<Customer> _customerRepository;

        public IndexModel(
            IRepository<Pizza> pizzaRepository,
            IRepository<Order> orderRepository,
            IRepository<Customer> customerRepository)
        {
            _pizzaRepository = pizzaRepository;
            _orderRepository = orderRepository;
            _customerRepository = customerRepository;
        }

        public Customer Customer { get; set; }

        public void OnGet()
        {
            PizzaList = _pizzaRepository.GetAllEntities().ToList();
            GetCurrentUser();

            HasOrders = Customer is not null && _orderRepository.Any(o => o.CurrentCustomerId == Customer.Id);
        }

        public IActionResult OnPostLogout()
        {
            RemoveUserId();
            Customer = null;

            return RedirectToPage(PageNames.Index);
        }

        private void GetCurrentUser()
        {
            int? userId = GetUserId();
            if (userId.HasValue)
            {
                Customer = _customerRepository.FirstOrDefault(c => c.Id == userId.Value);
            }
        }
    }
}

Pizzaria/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Pizzaria.Models;
using Pizzaria.Repositories;
using System.ComponentModel.DataAnnotations;

namespace Pizzaria.Pages
{
    public class LoginModel : PageModelBase
    {
        private readonly IRepository<Customer> _customerRepository;

        public LoginModel(IRepository<Customer> customerRepository)
        {
            _customerRepository = customerRepository;
        }

        [BindProperty]
        [Required]
        public string UserName { get; set; }

        [BindProperty]
        [Required]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Pasword must be  between  6 and 20 characters")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPostLogin()
        {
            return ValidUser()
                ? RedirectToPage(PageNames.Index)
                : Page();
        }

        private bool ValidUser()
        {
            var user = _customerRepository.FirstOrDefault(c => c.UserName == UserName);
            if (user is not null && user.Password.Equals(Password, StringComparison.InvariantCulture))
            {
                SetUserId(user?.Id ?? -1);
                return true;
            }

            return false;
        }
    }
}

Pizzaria/Pages/ThankYou.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Pizzaria.Pages
{
    public class ThankYouModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pizzaria/Pages/CreateOrder.cshtml
@page
@model Pizzaria.Pages.CreateOrderModel

@{
    ViewData["Title"] = "CreateOrder";
}

<h4>Order</h4>
<hr />
<div class="row">
    <form method="post">
        <h1 style="text-align:left;">@Model.SelectedPizza.Name</h1>
        <div class="d-flex flex-row">
            <div>
                @{
                    string imagePath = "~/Images/Pizzas/" + (@Model.SelectedPizza.Name + ".jpg");
                    <img src="@imagePath" class="col-6" asp-append-version="true" />
                }
            </div>
            <div class="d-flex flex-column">
                <div class="p-2">
                    <h5 style="text-align:left;">Base price: $@Model.SelectedPizza.BasePrice</h5>
                </div>

                <div class="form-group pb-4">
                    <input type="checkbox" asp-for="CurrentOrder.IsDoubleCheese" placeholder="Double Cheese" />Double Cheese (+$@Models.Order.DoubleCheesePrice)
                    <br />
                    <input type="checkbox" asp-for="CurrentOrder.IsTomato" placeholder="Tomato" />Tomato (+$@Models.Order.TomatoPrice)
                    <br />
                    <input type="checkbox" asp-for="CurrentOrder.IsBeef" placeholder="Beef" />Beef (+$@Models.Order.BeefPrice)
                    <br />
                </div>
            </div>
            <div class="p-2">
                <input type="hidden" asp-for="SelectedPizza.Id" />
            </div>
        </div>

        <div class="form-group pb-4">
            @if (@Model.HasLogin)
            {
                <input type="submit" class="btn btn-primary" value="Add" />
            }
            else
            {
                <div class="alert alert-danger" role="alert">Please Login and try again!</div>
            }
        </div>
    </form>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Pizzaria/Pages/Final.cshtml
@page
@model Pizzaria.Pages.FinalModel
@{
}

<form method="post">
    <h3>Orders</h3>
    <hr />

    <table class="table">
        <thead>
            <tr>
                <th>Pizza name</th>
                <th>Total Price</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var order in @Model.Orders)
            {
                <tr>
                    <th>@order.Pizza.Name</th>
                    <th>@order.TotalPrice</th>
                    <th>
                        <button type="submit" class="btn btn-danger" asp-page-handler="delete" asp-route-id="@order.Id">Delete</button>
                    </th>
                </tr>
            }
        </tbody>
    </table>

    <div>
        <h1>Grand total: $@Model.Orders.Sum(o => o.TotalPrice)</h1>
    </div>

    @if (@Model.Orders.Any())
    {
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Order" />
        </div>
    }
</form>

Pizzaria/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <div class="d-flex justify-content-end mb-3">
        @if (@Model.Customer == null)
        {
            <a class="btn btn-outline-dark" asp-page="Login">Login</a>
        }
        else
        {
            <form asp-page-handler="Logout" method="post">
                <button type="submit" class="btn btn-outline-dark">Logout</button>
            </form>
        }
    </div>

    <h1 class="display-4">Welcome <b>@Model.Customer?.Name </b>to my Pizzaria !!</h1>
    <p>What you want to order?</p>

    <div class="row">
        @foreach (var pizza in @Model.PizzaList)
        {
            string imagePath = "~/Images/Pizzas/" + (@pizza.Name + ".jpg");
            <div class="col-3 mb-5">
                <h1 style="text-align:left;">@pizza.Name</h1>
                <p style="text-align:left;">~$@pizza.BasePrice</p>
                <a class="pizza-img mt-1" style="float:left"
               asp-page="CreateOrder"
               asp-route-PizzaId="@pizza.Id">
                    <img src="@imagePath" class="w-100" asp-append-version="true" />
                </a>
                <br />
            </div>
        }
    </div>
    @if (@Model.HasOrders)
    {
        <a class="btn btn-primary mt-1" dis asp-area="" asp-page="Final">Finish my order</a>
    }
</div>

Pizzaria/Pages/Login.cshtml
@page
@model Pizzaria.Pages.LoginModel
@{
}
<div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card text-white" style="background-color:lightslategrey; border-radius: 1rem;">
                <div class="card-body p-5 text-center">
                    <div class="mb-md-5 mt-md-4 pb-5">
                        <form asp-page-handler="Login" method="post">
                            <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                            <p class="text-white-70 mb-5">Please enter your login and password!</p>

                            <div class="form-outline form-white mb-4">
                                <input type="text"
                                       asp-for="UserName"
                                       id="username"
                                       class="form-control form-control-lg"
                                       placeholder="Username" />
                                 <span asp-validation-for="UserName" class="text-danger"></span>
                            </div>

                            <div class="form-outline form-white mb-4">
                                <input type="password"
                                       asp-for="Password"
                                       id="password"
                                       class="form-control form-control-lg"
                                       placeholder="Password" />
                                 <span asp-validation-for="Password" class="text-danger"></span>
                            </div>

                            <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Pizzaria/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pizzaria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pizzaria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Pizza</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Final">Final</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pizza - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Pizzaria/Pages/ThankYou.cshtml
@page
@model Pizzaria.Pages.ThankYouModel
@{
}

<h3>THANK YOU FOR ORDER!</h3>
<a class="btn btn-primary mt-1" asp-page="Index">To home</a>